### ISSUE TITLE
User Authentication implementieren

### ISSUE THREAD

**Issue by Shochraos** [Lachstec/mc-hosting#15]

**Comment by Mac10goesBRRRT** [comment]
oder Auth0 als Provider. Wie läuft dass dann? Backend authentifiziert und reicht dann info ans Frontend durch?

**Comment by Lachstec** [comment]
Auth0 **ist** OAuth2, ist halt nur ein Dienstleister dafür. OAuth ist erstmal nur ein Protokoll. Das läuft dann ungefähr so:

1. User geht auf Login und wird zu Auth0 weitergeleitet
2. Anmeldung mit einer Option die der User auswählen kann
3. Auth0 setzt einen signierten Cookie / Token, welcher anzeigt, dass der User angemeldet ist
4. User sendet den Token bei folgenden Anfragen mit.
5. Backend kann dann den Token und die Signatur validieren

**Comment by Mac10goesBRRRT** [comment]
Okay, also so wie du sagst läuft es jetzt in der Theorie schon, wir können Token fetchen, die dann ans Backend senden und da gehts weiter.

Die Mechanik fürs fetchen existiert schon im Frontend, im Backend fehlt diese aber noch

**Comment by Lachstec** [comment]
Kann ich gerne implementieren, was brauchen wir dann im Backend konkret? ich denke mindestens mal:

- Token validieren
- Die Informationen vom User aus dem Token extrahieren.

Sonst noch was?

**Comment by Mac10goesBRRRT** [comment]
Genau, du holst dir aus dem Header den Auth Bearer, sendest diesen string an <AUTH_URL>/userinfo und bekommst als antwort die daten

**Comment by Lachstec** [comment]
Okay, ich setz mich parallel zu meinem provisioning-gedöns dran

**Comment by Lachstec** [comment]
Im dev mittlerweile möglich, wenn auch primitiv
