### ISSUE TITLE
CI Pipeline

### ISSUE THREAD

**Issue by Lachstec** [Lachstec/mc-hosting#8]
Wir sollten eine CI-Pipeline implementieren, wenn die Projektstruktur steht. Die Pipeline sollte sicherstellen, dass neuer Code bestimmte Anforderungen erfüllt und Tests (wenn vorhanden) durchlaufen. Mögliche Anforderungen / Tätigkeiten sind:

- [x] Codeformattierung überprüfen
- [x] Codequalität (Linting)
- [x] Testing
- [ ] (Test Coverage)
- [x] Docker Container bauen
- [x] Container Images in Registry pushen

**Comment by Mac10goesBRRRT** [comment]
Hey, hab hier auch mal prettier fürs Frontend gebastelt #29
